name: 'Create Release'
description: 'Create release base standard-version package'
author: 'Payadel'

# Here we define the inputs, which can be set
# from the workflow file and are consumed in our code
inputs:
  git-email:
    description: 'git user.email config for commit. Default: github-action@github.com'
    default: 'github-action@github.com'
    required: false
  git-user-name:
    description: 'git user.name config for commit. Default: Github Action'
    default: 'Github Action'
    required: false
  version:
    description: 'Release version. Leave empty for auto generate. Default: ""'
    default: ''
    required: false
  skip-changelog:
    description: 'Skip generate changelog file or not? Default: true'
    default: "true"
    required: false
  skip-release-file:
    description: 'Skip create release file or not? Default: true'
    default: 'true'
    required: false
  release-file-name:
    description: 'Release file name. Default: release'
    default: "release"
    required: false
  release-directory:
    description: 'Where are the release files?. Default: .'
    default: '.'
    required: false
  create-pr-for-branch:
    description: 'Create pull request for any branch? Leave empty for skip. Default: ""'
    required: false
    default: ''
  is-test-mode:
    description: "Set the value 'true' for testing purposes. Default: false"
    required: false
    default: 'false'
  changelog-version-regex:
    description: 'The regex with which we find the version lines in the changelog file.'
    default: ''
    required: false
outputs:
  version:
    description: 'Release version'
  pull-request-url:
    description: 'The pull request link that has been created. ('' if not created)'
  releaseFileName:
    description: 'Release file name'
  changelog:
    description: 'New changelog text'

runs:
  using: 'node16'
  main: 'dist/index.js'
